version: '3.8'
services:
  mysql:
    image: m.daocloud.io/docker.io/library/mysql:8.0
    container_name: outdoor-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qq2027681066
      MYSQL_DATABASE: outdoor_demo
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - outdoor-net

  redis:
    image: m.daocloud.io/docker.io/library/redis:latest
    container_name: outdoor-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - outdoor-net

  minio:
    image: m.daocloud.io/docker.io/minio/minio
    container_name: outdoor-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: qq2027681066
      MINIO_API_CORS_ALLOW_ORIGIN: "*"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - outdoor-net

volumes:
  mysql-data:
  redis-data:
  minio-data:

networks:
  outdoor-net:
    driver: bridge
